include: package:lint/analysis_options.yaml

linter:
  rules:
    # Não é necessário ordenar alfabeticamente os imports de dependências
    # nos arquivos. Acho desnecessário
    sort_pub_dependencies: false
    avoid_bool_literals_in_conditional_expressions: false
